### ISSUE TITLE
ProxyError: Unexpected SOCKS version number: 0

### ISSUE THREAD

**Issue by TensorTom** [romis2012/aiohttp-socks#23]
I keep getting this exception only part of the time and not sure how to prevent it:

```bash
Traceback (most recent call last):
  File "/home/user/Projects/project/scraping.py", line 762, in index_matches
    async with session.get(link, headers=AIOHTTP_HEADERS, max_redirects=30) as resp:
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp/client.py", line 480, in _request
    conn = await self._connector.connect(
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 858, in _create_connection
    _, proto = await self._create_direct_connection(
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp/connector.py", line 980, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/aiohttp_socks/connector.py", line 58, in _wrap_create_connection
    sock = await proxy.connect(host, port, timeout=connect_timeout)
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/python_socks/_proxy_async_aio.py", line 96, in connect
    await self._connect(_socket=_socket)
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/python_socks/_proxy_async_aio.py", line 123, in _connect
    await self._negotiate()
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/python_socks/_proxy_async_aio.py", line 155, in _negotiate
    await proto.negotiate()
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/python_socks/_proto_socks5_async.py", line 41, in negotiate
    await self._socks_auth()
  File "/home/user/.cache/pypoetry/virtualenvs/project-w2kGw2C9-py3.9/lib/python3.9/site-packages/python_socks/_proto_socks5_async.py", line 58, in _socks_auth
    raise ProxyError(
python_socks._errors.ProxyError: Unexpected SOCKS version number: 0

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

My code: https://github.com/TensorTom/actproxy/blob/master/actproxy/__init__.py :: `aiohttp_rotate()`

It's a wrapper for rotating proxies with ActProxy. I know I shouldn't be recreating the session for each connection but I haven't tried to tackle rotation within the same session yet. Any idea how to get rid of the exception?

Python: 3.9
OS: Linux x64
Proto: IPv4 + SOCKS5
Auth: Username/Password

**Comment by romis2012** [comment]
`python_socks._errors.ProxyError: Unexpected SOCKS version number: 0` error message means that your proxy server violates SOCKS5 protocol.

> I know I shouldn't be recreating the session for each connection but I haven't tried to tackle rotation within the same session yet

Each ClientSession should use its own ProxyConnector, but this is not relevant to this error
