### ISSUE TITLE
Can ProxyConnector.from_url support a proxy_ssl parameter?

### ISSUE THREAD

**Issue by st3fan** [romis2012/aiohttp-socks#37]
Unlike the `SyncProxyTransport.from_url ` in `httpx-socks`, the `ProxyConnector.from_url()` call in this project does not support the `proxy_ssl` parameter.

Is there a technical reason for this? If not, would you accept a pull request to add this functionality? It looks like this could be added and then simply passed through to `AsyncioProxy` ? Is that assumption correct?

**Comment by st3fan** [comment]
I did something really simple to try this, adding `proxy_ssl` to the call to `Proxy.create()` in `_wrap_create_connection()`:

```python
    # noinspection PyMethodOverriding
    async def _wrap_create_connection(self, protocol_factory,
                                      host, port, *, ssl, **kwargs):
        proxy = Proxy.create(
            proxy_type=self._proxy_type,
            host=self._proxy_host,
            port=self._proxy_port,
	    username=self._proxy_username,
	    password=self._proxy_password,
            proxy_ssl=self._proxy_ssl,
	    rdns=self._rdns,

            loop=self._loop,
	)
        ...
```

But this results in an `TypeError: transport <asyncio.sslproto._SSLProtocolTransport object at 0xffffa24452a0> is not supported by start_tls()` error deep inside the `asyncio` framework:

```
Traceback (most recent call last):
  File "/home/stefan.arentz/./aiohttp_via_socks.py", line 25, in <module>
    asyncio.run(main())
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/stefan.arentz/./aiohttp_via_socks.py", line 20, in main
    async with session.get("https://www.example.com") as response:
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/aiohttp_socks/connector.py", line 61, in _wrap_create_connection
    stream = await proxy.connect(
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/python_socks/async_/asyncio/v2/_proxy.py", line 62, in connect
    return await self._connect(_stream)
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/python_socks/async_/asyncio/v2/_proxy.py", line 103, in _connect
    self._stream = await self._stream.start_tls(
  File "/home/stefan.arentz/.venv/lib64/python3.10/site-packages/python_socks/async_/asyncio/v2/_stream.py", line 82, in start_tls
    transport = await loop_start_tls(
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 1220, in start_tls
    raise TypeError(
TypeError: transport <asyncio.sslproto._SSLProtocolTransport object at 0xffffa24452a0> is not supported by start_tls()
```

**Comment by st3fan** [comment]
Maybe this is https://github.com/python/cpython/issues/81360 ?

**Comment by st3fan** [comment]
> Maybe this is [python/cpython#81360](https://github.com/python/cpython/issues/81360) ?

To answer my own question: I installed Python 3.11.rc1 and things work well there. On Python 3.10.6 I get the above error.

So, dead end?

**Comment by romis2012** [comment]
This issue (asyncio "TLS in TLS" connections) is well describes here: https://github.com/aio-libs/aiohttp/discussions/6044, https://github.com/aio-libs/aiohttp/issues/2722,  https://github.com/romis2012/python-socks/issues/10, https://github.com/romis2012/python-socks/issues/4, https://bugs.python.org/issue37179,  https://github.com/encode/httpx/issues/1434, https://github.com/encode/httpcore/issues/254


This feature is planned to be added (with known limitations) in the next minor release.

**Comment by romis2012** [comment]
`proxy_ssl` argument added in version 0.8.0
