### ISSUE TITLE
Private Internet Access - python_socks._errors.ProxyError: Host unreachable

### ISSUE THREAD

**Issue by StevensNJD4** [romis2012/aiohttp-socks#38]
Hello,

I have been getting `python_socks._errors.ProxyError: Host unreachable` with any URL I try with PIA's socks5 proxy. I've tried ensuring that all dependencies are installed. An http proxy does work but would like to use PIA's.

Sample code:
```
import asyncio
import aiohttp
from aiohttp_socks import ProxyType, ProxyConnector, ChainProxyConnector

async def main():
    proxy = 'socks5://...@proxy-nl.privateinternetaccess.com:1080'
    connector = ProxyConnector.from_url(proxy, rdns=True)

    async with aiohttp.ClientSession(connector=connector) as session:
        async with session.get('https://google.com') as resp:
            print(await resp.text())

asyncio.run(main())
```
Using it with regular `requests` works as expected.

Any help would be appreciated.

**Comment by StevensNJD4** [comment]
It does work with a http URL...

**Comment by romis2012** [comment]
Are you sure that you specify the correct proxy address?

Try some other proxy client, for example requests:
```
pip install requests[socks] -U
...
proxy = 'socks5://...@proxy-nl.privateinternetaccess.com:1080'
res = requests.get(url='https://google.com', proxies={'https': proxy})
print(res.text)
```

Also try to specify some another target url, e.g. `https://check-host.net/ip` (`ProxyError: Host unreachable` usually means that proxy server is unable to connect to the target host)

> ... would like to use PIA's

`aiohttp-socks` works perfectly with any proxy servers that support socks5 protocol

**Comment by StevensNJD4** [comment]
Yes, I've tried it with requests and it works as expected.

When I request a http URL with aiohttp-socks, and the PIA proxy, it works as expected. Only https URLs give me that error.

**Comment by romis2012** [comment]
Please provide a complete stack trace of an Exception

**Comment by StevensNJD4** [comment]
```
Traceback (most recent call last):
  File "/nhl/aiohttpsocks.py", line 13, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/nhl/aiohttpsocks.py", line 10, in main
    async with session.get('https://google.com') as resp:
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.10/dist-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.10/dist-packages/aiohttp_socks/connector.py", line 72, in _wrap_create_connection
    stream = await proxy.connect(
  File "/usr/local/lib/python3.10/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 62, in connect
    return await self._connect(_stream)
  File "/usr/local/lib/python3.10/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 100, in _connect
    await self._negotiate()
  File "/usr/local/lib/python3.10/dist-packages/python_socks/async_/asyncio/v2/_proxy.py", line 160, in _negotiate
    await proto.negotiate()
  File "/usr/local/lib/python3.10/dist-packages/python_socks/_proto/socks5_async.py", line 43, in negotiate
    await self._socks_connect()
  File "/usr/local/lib/python3.10/dist-packages/python_socks/_proto/socks5_async.py", line 83, in _socks_connect
    res.validate()
  File "/usr/local/lib/python3.10/dist-packages/python_socks/_proto/socks5.py", line 199, in validate
    raise ProxyError(msg, self.reply)
python_socks._errors.ProxyError: Host unreachable
```

**Comment by romis2012** [comment]
This error means that proxy server cannot connect to target host,  as I mentioned above. It does not depend on whether you are connecting to target host via http or https transport (the error occurs before a secure connection is established). Have you tried specifying other target url?

**Comment by StevensNJD4** [comment]
It happens with any https url I try. It works with http URLs and works fine with requests.

**Comment by StevensNJD4** [comment]
ok, i'm wrong. it appears the dns isn't working.

my apologies. http://httpbin.org doesn't work but its ip does

**Comment by StevensNJD4** [comment]
Just tried it on my main PC and I get the same error.

Would you have any idea why it can't resolve domain names?

**Comment by romis2012** [comment]
Some socks5 servers do not support hostname resolution at all. In this case you should pass `rdns=False` to resolve domain locally

**Comment by StevensNJD4** [comment]
Thank you
